# -*- coding: utf-8 -*-
"""Bluetooth.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e27pInmecjMrpz2zFh_Hvg8gh2vb1rF5
"""

#install pybluez2
import bluetooth
import pandas as pd
import socket

mySocket = socket.socket()
hostname="127.0.0.4"# 127.0.0.1 #0.0.0.0
port=7000
mySocket.bind((hostname,port))
mySocket.listen(1)
conn , addr = mySocket.accept()
print("Connected")

nearby_devices = bluetooth.discover_devices(lookup_names=True)
file_path = r"D:/Uni/semester 7/CS484/Project/bluetooth/bloutooth.xlsx"  # Replace with your Excel file path
users_df = pd.read_excel(file_path)
# Extract registered MAC addresses for quick lookup
registered_macs = set(users_df["mac_address"])

print("found %d devices" % len(nearby_devices))

for addr, name in nearby_devices:
    if addr in registered_macs:
        # Fetch user details from the Excel file
        user_data = users_df.loc[users_df["mac_address"] == addr]
        user = user_data.iloc[0]  # Get the matched user profile
                        
        print(f"Login successful for user: {user['name']}")
        print(f"gender: {user['gender']}")
        gender= user['gender']
        print(f"deal: {user['deal']}")
        print(user['gender'])
        msg2 =bytes(user['gender'], 'utf-8')
        conn.send(msg2)
        conn.close()
        break
    